version: "3"

services:

  zeo:
    image: bikalims:latest
    command: zeo
    volumes:
      - ./data:/data

  instance1:
    image: bikalims:latest
    ports:
      - 8081:8080
    links:
      - zeo
    environment:
      ZEO_ADDRESS: "zeo:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/home/senaite/senaitelims/src

  instance2:
    image: senaite:latest
    ports:
      - 8082:8080
    links:
      - zeo
    environment:
      ZEO_ADDRESS: "zeo:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/home/senaite/senaitelims/src

volumes:
  data:
    external: true
  src:
    external: true
